# Site settings
title: KLamp Works
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My blog, mostly about programming, security, privacy and Unixy things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yukipyon.me" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: klampworks
host: 192.168.100.9
#detach: true

# Build settings
markdown: kramdown
